[default]
TITLE = 'TryCars'
# Flask-Mail
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = 0
MAIL_USE_SSL = 1
MAIL_DEFAULT_SENDER = 'noreply.trycars@gmail.com'

[development]
SQLALCHEMY_DATABASE_URI = "sqlite:///base.db"