[default]
TITLE = 'TryCars'
# Flask-Security
SQLALCHEMY_TRACK_MODIFICATIONS = 0
SECURITY_RECOVERABLE = 1
SECURITY_TRACKABLE = 1
SECURITY_CHANGEABLE = 1
SECURITY_CONFIRMABLE = 1
SECURITY_REGISTERABLE = 1
SECURITY_PASSWORD_COMPLEXITY_CHECKER = 'zxcvbn'
WTF_CSRF_CHECK_DEFAULT = 0

[development]
SQLALCHEMY_DATABASE_URI = "sqlite:///base.db"