"""empty message

Revision ID: 027a9c09a30d
Revises: 29ab8d9ecb68
Create Date: 2024-03-08 15:59:54.539833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027a9c09a30d'
down_revision = '29ab8d9ecb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fs_uniquifier', new_column_name='alter_id')
        # batch_op.add_column(sa.Column('alter_id', sa.String(length=64), nullable=False))
        # batch_op.create_unique_constraint(None, ['alter_id'])
        # batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('alter_id', new_column_name='fs_uniquifier')
        # batch_op.add_column(sa.Column('fs_uniquifier', sa.VARCHAR(length=64), nullable=False))
        # batch_op.drop_constraint(None, type_='unique')
        # batch_op.drop_column('alter_id')

    # ### end Alembic commands ###
