"""disable trackable user

Revision ID: 29ab8d9ecb68
Revises: 
Create Date: 2024-02-21 13:43:13.249782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ab8d9ecb68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_login_ip')
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('last_login_ip')
        batch_op.drop_column('current_login_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_login_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_login_ip', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('current_login_ip', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
